/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceBrokerRole;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Organization.InsBrokerOrganization;
import model.Organization.Organization;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import userinterface.LoginJPanel;

/**
 *
 * @author Akshita
 */
public class InsuranceBrokerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private InsBrokerOrganization insuranceAgentOrganization;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;

    public InsuranceBrokerWorkAreaJPanel(JPanel jpanel, UserAccount userAccount, Organization organization, Enterprise enterprise,DB4OUtil dB4OUtil, EcoSystem ecosystem) {
        initComponents();
        
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Broker.gif"));
        icon.getImage().flush();
        jLabel5.setIcon(icon);
        
        this.userProcessContainer = jpanel;
        this.userAccount = userAccount;
        this.insuranceAgentOrganization = (InsBrokerOrganization) organization;
        this.enterprise = enterprise;
        this.ecosystem=ecosystem;
        this.dB4OUtil=dB4OUtil;
        
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnAddNewUser = new javax.swing.JButton();
        btnProcessInsuranceRequests = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnLogoutPatient = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 17, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("INSURANCE BROKER WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 6, 410, -1));

        jPanel1.setBackground(new java.awt.Color(22, 27, 34));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(188, 188, 188));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BROKER TASKS");

        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel.setText("Enterprise :");

        valueLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(188, 188, 188));
        valueLabel.setText("<value>");

        btnAddNewUser.setBackground(new java.awt.Color(22, 27, 34));
        btnAddNewUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddNewUser.setForeground(new java.awt.Color(188, 188, 188));
        btnAddNewUser.setText("Add New Customer");
        btnAddNewUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAddNewUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAddNewUserFocusLost(evt);
            }
        });
        btnAddNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewUserMouseExited(evt);
            }
        });
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });

        btnProcessInsuranceRequests.setBackground(new java.awt.Color(22, 27, 34));
        btnProcessInsuranceRequests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProcessInsuranceRequests.setForeground(new java.awt.Color(188, 188, 188));
        btnProcessInsuranceRequests.setText("Process Insurance Requests");
        btnProcessInsuranceRequests.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnProcessInsuranceRequestsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnProcessInsuranceRequestsFocusLost(evt);
            }
        });
        btnProcessInsuranceRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcessInsuranceRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcessInsuranceRequestsMouseExited(evt);
            }
        });
        btnProcessInsuranceRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessInsuranceRequestsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("You can perform the below tasks.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAddNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcessInsuranceRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 216, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcessInsuranceRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddNewUser, btnProcessInsuranceRequests});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 420, 550));

        btnLogoutPatient.setBackground(new java.awt.Color(13, 17, 23));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Broker.gif"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAddNewUserFocusGained
        // TODO add your handling code here:
        btnAddNewUser.setForeground(new Color(255, 255, 255));
        btnAddNewUser.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAddNewUserFocusGained

    private void btnAddNewUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAddNewUserFocusLost
        // TODO add your handling code here:
        btnAddNewUser.setForeground(new Color(188, 188, 188));
        btnAddNewUser.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAddNewUserFocusLost

    private void btnAddNewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewUserMouseEntered
        // TODO add your handling code here:
        btnAddNewUser.setForeground(new Color(255, 255, 255));
        btnAddNewUser.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAddNewUserMouseEntered

    private void btnAddNewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewUserMouseExited
        // TODO add your handling code here:
        btnAddNewUser.setForeground(new Color(188, 188, 188));
        btnAddNewUser.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAddNewUserMouseExited

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed

        String policyNumber = UUID.randomUUID().toString().substring(0, 7);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddNewPolicyHolderJPanel", new AddNewPolicyHolderJPanel(userProcessContainer, userAccount, enterprise, policyNumber));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnAddNewUserActionPerformed

    private void btnProcessInsuranceRequestsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsFocusGained
        // TODO add your handling code here:
        btnProcessInsuranceRequests.setForeground(new Color(255, 255, 255));
        btnProcessInsuranceRequests.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnProcessInsuranceRequestsFocusGained

    private void btnProcessInsuranceRequestsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsFocusLost
        // TODO add your handling code here:
        btnProcessInsuranceRequests.setForeground(new Color(188, 188, 188));
        btnProcessInsuranceRequests.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnProcessInsuranceRequestsFocusLost

    private void btnProcessInsuranceRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsMouseEntered
        // TODO add your handling code here:
        btnProcessInsuranceRequests.setForeground(new Color(255, 255, 255));
        btnProcessInsuranceRequests.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnProcessInsuranceRequestsMouseEntered

    private void btnProcessInsuranceRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsMouseExited
        // TODO add your handling code here:
        btnProcessInsuranceRequests.setForeground(new Color(188, 188, 188));
        btnProcessInsuranceRequests.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnProcessInsuranceRequestsMouseExited

    private void btnProcessInsuranceRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessInsuranceRequestsActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ProcessInsuranceRequestsJPanel", new AllInsuranceRequestsJPanel(userProcessContainer, userAccount, enterprise, insuranceAgentOrganization));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnProcessInsuranceRequestsActionPerformed

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        userProcessContainer.removeAll();
        LoginJPanel lp = new LoginJPanel(ecosystem, dB4OUtil, userProcessContainer);
        userProcessContainer.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JButton btnProcessInsuranceRequests;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
