package userinterface.AdministrativeRole;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.NGOEnterprise;
import model.Enterprise.InsuranceEnterprise;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import userinterface.LoginJPanel;

/**
 *
 * @author Sai Dutt
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil;

    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, EcoSystem ecoSystem, DB4OUtil dB4OUtil) {
        
        initComponents();

        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Work time.gif"));
        icon.getImage().flush();
        jLabel4.setIcon(icon);

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        this.dB4OUtil = dB4OUtil;
        valueLabel.setText(enterprise.getName());

        if (enterprise instanceof NGOEnterprise || enterprise instanceof InsuranceEnterprise) {
            
            btnRequestFunds.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnLogoutPatient = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        userJButton = new javax.swing.JButton();
        btnRequestFunds = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 17, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("ADMINISTRATIVE WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, 380, -1));

        btnLogoutPatient.setBackground(new java.awt.Color(13, 17, 23));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));

        jPanel1.setBackground(new java.awt.Color(22, 27, 34));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(188, 188, 188));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADMIN TASKS");

        enterpriseLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel.setText("Enterprise :");

        valueLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(188, 188, 188));
        valueLabel.setText("<value>");

        manageOrganizationJButton.setBackground(new java.awt.Color(22, 27, 34));
        manageOrganizationJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageOrganizationJButton.setForeground(new java.awt.Color(188, 188, 188));
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manageOrganizationJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manageOrganizationJButtonFocusLost(evt);
            }
        });
        manageOrganizationJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageOrganizationJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageOrganizationJButtonMouseExited(evt);
            }
        });
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        manageEmployeeJButton.setBackground(new java.awt.Color(22, 27, 34));
        manageEmployeeJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(188, 188, 188));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manageEmployeeJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manageEmployeeJButtonFocusLost(evt);
            }
        });
        manageEmployeeJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageEmployeeJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageEmployeeJButtonMouseExited(evt);
            }
        });
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });

        userJButton.setBackground(new java.awt.Color(22, 27, 34));
        userJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userJButton.setForeground(new java.awt.Color(188, 188, 188));
        userJButton.setText("Manage User Account");
        userJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userJButtonFocusLost(evt);
            }
        });
        userJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userJButtonMouseExited(evt);
            }
        });
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });

        btnRequestFunds.setBackground(new java.awt.Color(22, 27, 34));
        btnRequestFunds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRequestFunds.setForeground(new java.awt.Color(188, 188, 188));
        btnRequestFunds.setText("Request Funds");
        btnRequestFunds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRequestFundsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnRequestFundsFocusLost(evt);
            }
        });
        btnRequestFunds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRequestFundsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRequestFundsMouseExited(evt);
            }
        });
        btnRequestFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestFundsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("You can perform the below tasks.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRequestFunds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRequestFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRequestFunds, manageEmployeeJButton, manageOrganizationJButton, userJButton});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 420, 550));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Work time.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 620, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnRequestFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestFundsActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestFundsJPanel", new RequestFundsJPanel(userProcessContainer, enterprise, userAccount, ecoSystem));
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnRequestFundsActionPerformed

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        userProcessContainer.removeAll();
        LoginJPanel lp = new LoginJPanel(ecoSystem, dB4OUtil, userProcessContainer);
        userProcessContainer.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecoSystem);

    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void manageOrganizationJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonMouseEntered
        // TODO add your handling code here:
        manageOrganizationJButton.setForeground(new Color(255, 255, 255));
        manageOrganizationJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_manageOrganizationJButtonMouseEntered

    private void manageOrganizationJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonMouseExited
        // TODO add your handling code here:
        manageOrganizationJButton.setForeground(new Color(188, 188, 188));
        manageOrganizationJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_manageOrganizationJButtonMouseExited

    private void manageOrganizationJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonFocusGained
        // TODO add your handling code here:
        manageOrganizationJButton.setForeground(new Color(255, 255, 255));
        manageOrganizationJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_manageOrganizationJButtonFocusGained

    private void manageOrganizationJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonFocusLost
        // TODO add your handling code here:
        manageOrganizationJButton.setForeground(new Color(188, 188, 188));
        manageOrganizationJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_manageOrganizationJButtonFocusLost

    private void manageEmployeeJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonFocusGained
        // TODO add your handling code here:
        manageEmployeeJButton.setForeground(new Color(255, 255, 255));
        manageEmployeeJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_manageEmployeeJButtonFocusGained

    private void manageEmployeeJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonFocusLost
        // TODO add your handling code here:
        manageEmployeeJButton.setForeground(new Color(188, 188, 188));
        manageEmployeeJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_manageEmployeeJButtonFocusLost

    private void manageEmployeeJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonMouseEntered
        // TODO add your handling code here:
        manageEmployeeJButton.setForeground(new Color(255, 255, 255));
        manageEmployeeJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_manageEmployeeJButtonMouseEntered

    private void manageEmployeeJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonMouseExited
        // TODO add your handling code here:
        manageEmployeeJButton.setForeground(new Color(188, 188, 188));
        manageEmployeeJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_manageEmployeeJButtonMouseExited

    private void userJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userJButtonFocusGained
        // TODO add your handling code here:
        userJButton.setForeground(new Color(255, 255, 255));
        userJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_userJButtonFocusGained

    private void userJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userJButtonFocusLost
        // TODO add your handling code here:
        userJButton.setForeground(new Color(188, 188, 188));
        userJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_userJButtonFocusLost

    private void userJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userJButtonMouseExited
        // TODO add your handling code here:
        userJButton.setForeground(new Color(188, 188, 188));
        userJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_userJButtonMouseExited

    private void userJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userJButtonMouseEntered
        // TODO add your handling code here:
        userJButton.setForeground(new Color(255, 255, 255));
        userJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_userJButtonMouseEntered

    private void btnRequestFundsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRequestFundsFocusGained
        // TODO add your handling code here:
        btnRequestFunds.setForeground(new Color(255, 255, 255));
        btnRequestFunds.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnRequestFundsFocusGained

    private void btnRequestFundsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRequestFundsFocusLost
        // TODO add your handling code here:
        btnRequestFunds.setForeground(new Color(188, 188, 188));
        btnRequestFunds.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnRequestFundsFocusLost

    private void btnRequestFundsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequestFundsMouseEntered
        // TODO add your handling code here:
        btnRequestFunds.setForeground(new Color(255, 255, 255));
        btnRequestFunds.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnRequestFundsMouseEntered

    private void btnRequestFundsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequestFundsMouseExited
        // TODO add your handling code here:
        btnRequestFunds.setForeground(new Color(188, 188, 188));
        btnRequestFunds.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnRequestFundsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JButton btnRequestFunds;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
