/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalAccountantRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthCenterEnterprise;
import Business.Organization.AccountantOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import userinterface.LoginJPanel;

/**
 *
 * @author Sai Dutt & Ganesh
 */
public class AccountantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AccountantOrganization accountantOrganization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil;

    public AccountantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AccountantOrganization accountantOrganization, Enterprise enterprise, EcoSystem ecosystem,DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.accountantOrganization = accountantOrganization;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.ecoSystem = ecosystem;
        this.dB4OUtil=dB4OUtil;
        populateAllPatientsTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAppointment = new javax.swing.JButton();
        btnProcessMedicalBillings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllPatients = new javax.swing.JTable();
        btnReport = new javax.swing.JButton();
        btnLogoutPatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 17, 23));
        setForeground(new java.awt.Color(188, 188, 188));
        setPreferredSize(new java.awt.Dimension(1190, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateAppointment.setBackground(new java.awt.Color(22, 27, 34));
        btnCreateAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateAppointment.setForeground(new java.awt.Color(188, 188, 188));
        btnCreateAppointment.setText("Create Appointment");
        btnCreateAppointment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCreateAppointmentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCreateAppointmentFocusLost(evt);
            }
        });
        btnCreateAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateAppointmentMouseExited(evt);
            }
        });
        btnCreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppointmentActionPerformed(evt);
            }
        });
        add(btnCreateAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 162, 34));

        btnProcessMedicalBillings.setBackground(new java.awt.Color(22, 27, 34));
        btnProcessMedicalBillings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProcessMedicalBillings.setForeground(new java.awt.Color(188, 188, 188));
        btnProcessMedicalBillings.setText("Process Medical Billings");
        btnProcessMedicalBillings.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnProcessMedicalBillingsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnProcessMedicalBillingsFocusLost(evt);
            }
        });
        btnProcessMedicalBillings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcessMedicalBillingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcessMedicalBillingsMouseExited(evt);
            }
        });
        btnProcessMedicalBillings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessMedicalBillingsActionPerformed(evt);
            }
        });
        add(btnProcessMedicalBillings, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 180, 32));

        tblAllPatients.setBackground(new java.awt.Color(13, 17, 23));
        tblAllPatients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAllPatients.setForeground(new java.awt.Color(188, 188, 188));
        tblAllPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Patient Name", "Phone Number", "Address", "Treatment Status", "Appointment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllPatients);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1110, 380));

        btnReport.setBackground(new java.awt.Color(22, 27, 34));
        btnReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(188, 188, 188));
        btnReport.setText("Show Patient Report");
        btnReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnReportFocusLost(evt);
            }
        });
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, 30));

        btnLogoutPatient.setBackground(new java.awt.Color(22, 27, 34));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("RECEPTIONIST WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, 380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppointmentActionPerformed

        String patientId = UUID.randomUUID().toString().substring(0, 7);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CreateAppointmentJPanel", new CreateAppointmentJPanel(userProcessContainer, userAccount, enterprise, ecoSystem, patientId));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateAppointmentActionPerformed

    private void btnProcessMedicalBillingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessMedicalBillingsActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ProcessMedicalBillingsJPanel", new ProcessMedicalBillingsJPanel(userProcessContainer, userAccount, enterprise, accountantOrganization, ecoSystem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessMedicalBillingsActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        List<Patient> underTreatmentPatients = new ArrayList<>();
        List<Patient> treatedPatients = new ArrayList<>();
        DefaultPieDataset defaultPieDataset = new DefaultPieDataset();
        List<Patient> patients = ((HealthCenterEnterprise) enterprise).getPatientDirectory().getPatients();
        for (Patient patient : patients) {
            if (patient.isIsTreatmentFinished()) {
                treatedPatients.add(patient);
            } else {
                underTreatmentPatients.add(patient);
            }
        }
        defaultPieDataset.setValue("Patient still under treatment", underTreatmentPatients.size());
        defaultPieDataset.setValue("Patient Treated Successfully", treatedPatients.size());
        JFreeChart chart = ChartFactory.createPieChart("Patient Status Pie Chart", defaultPieDataset, true, true, true);
        PiePlot piePlot = (PiePlot) chart.getPlot();
        ChartFrame frame = new ChartFrame("Patient Status Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(500, 500);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        userProcessContainer.removeAll();
        LoginJPanel lp = new LoginJPanel(ecoSystem, dB4OUtil, userProcessContainer);
        userProcessContainer.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void btnCreateAppointmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreateAppointmentFocusGained
        // TODO add your handling code here:
        btnCreateAppointment.setForeground(new Color(255, 255, 255));
        btnCreateAppointment.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreateAppointmentFocusGained

    private void btnCreateAppointmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreateAppointmentFocusLost
        // TODO add your handling code here:
        btnCreateAppointment.setForeground(new Color(188, 188, 188));
        btnCreateAppointment.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreateAppointmentFocusLost

    private void btnCreateAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAppointmentMouseEntered
        // TODO add your handling code here:
        btnCreateAppointment.setForeground(new Color(255, 255, 255));
        btnCreateAppointment.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreateAppointmentMouseEntered

    private void btnCreateAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAppointmentMouseExited
        // TODO add your handling code here:
        btnCreateAppointment.setForeground(new Color(188, 188, 188));
        btnCreateAppointment.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreateAppointmentMouseExited

    private void btnReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnReportFocusGained
        // TODO add your handling code here:
        btnReport.setForeground(new Color(255, 255, 255));
        btnReport.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnReportFocusGained

    private void btnReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnReportFocusLost
        // TODO add your handling code here:
        btnReport.setForeground(new Color(188, 188, 188));
        btnReport.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnReportFocusLost

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        btnReport.setForeground(new Color(255, 255, 255));
        btnReport.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        btnReport.setForeground(new Color(188, 188, 188));
        btnReport.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnReportMouseExited

    private void btnProcessMedicalBillingsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProcessMedicalBillingsFocusGained
        // TODO add your handling code here:
        btnProcessMedicalBillings.setForeground(new Color(255, 255, 255));
        btnProcessMedicalBillings.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnProcessMedicalBillingsFocusGained

    private void btnProcessMedicalBillingsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProcessMedicalBillingsFocusLost
        // TODO add your handling code here:
        btnProcessMedicalBillings.setForeground(new Color(188, 188, 188));
        btnProcessMedicalBillings.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnProcessMedicalBillingsFocusLost

    private void btnProcessMedicalBillingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessMedicalBillingsMouseEntered
        // TODO add your handling code here:
         btnProcessMedicalBillings.setForeground(new Color(255, 255, 255));
        btnProcessMedicalBillings.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnProcessMedicalBillingsMouseEntered

    private void btnProcessMedicalBillingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessMedicalBillingsMouseExited
        // TODO add your handling code here:
        btnProcessMedicalBillings.setForeground(new Color(188, 188, 188));
        btnProcessMedicalBillings.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnProcessMedicalBillingsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JButton btnProcessMedicalBillings;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllPatients;
    // End of variables declaration//GEN-END:variables

    public void populateAllPatientsTable() {
        List<Patient> patients = ((HealthCenterEnterprise) enterprise).getPatientDirectory().getPatients();
        DefaultTableModel dtm = (DefaultTableModel) tblAllPatients.getModel();
        dtm.setRowCount(0);
        for (Patient patient : patients) {
            Object[] row = new Object[6];

            row[0] = patient;
            row[1] = patient.getPatientFirstName() + " " + patient.getPatientLastName();
            row[2] = patient.getContactNumber();
            row[3] = patient.getPatientAddress();
            row[4] = patient.isIsTreatmentFinished() ? "Treatment Complete" : "Treatment In Progress";
            row[5] = patient.getAppointmentDate();

            dtm.addRow(row);
        }

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dtm);
        tblAllPatients.setRowSorter(sorter);
    }
}
