/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalAccountantRole;

import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.HealthCenterEnterprise;
import model.Enterprise.InsuranceEnterprise;
import model.Insurance.Insurance;
import model.InsuranceCustomer.InsuranceCustomer;
import model.Network.HealthcareNetwork;
import model.Organization.DoctorOrganization;
import model.Organization.Organization;
import model.Patient.Patient;
import model.UserAccount.UserAccount;
import model.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author Sai Dutt & Ganesh
 */
public class CreateAppointmentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    private String patientId;

    CreateAppointmentJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem, String patientId) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecoSystem;
        this.patientId = patientId;

        populateField();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtPatientId11 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientSSN = new javax.swing.JTextField();
        txtPatientIdentifier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        radioBtnOther = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        btnFindPatient = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        radioBtnPatientInsuranceYes = new javax.swing.JRadioButton();
        radioBtnPatientInsuranceNo = new javax.swing.JRadioButton();
        lblHavePolicy = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        lblInsCompany = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtReasonForVisit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblPolicyNum = new javax.swing.JLabel();
        txtPolicyNum = new javax.swing.JTextField();
        txtInsuranceCompany = new javax.swing.JTextField();
        txtPolicyName = new javax.swing.JTextField();
        lblCoverage = new javax.swing.JLabel();
        txtCoverage = new javax.swing.JTextField();
        btnResetPolicyNum = new javax.swing.JButton();
        btnFindInsurance = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jLabel14.setText("Middle Name :");

        setBackground(new java.awt.Color(13, 17, 23));
        setForeground(new java.awt.Color(188, 188, 188));
        setPreferredSize(new java.awt.Dimension(1190, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 51, -1, 30));

        txtDate.setBackground(new java.awt.Color(22, 27, 34));
        txtDate.setForeground(new java.awt.Color(188, 188, 188));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 52, 130, 30));

        jPanel1.setBackground(new java.awt.Color(22, 27, 34));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(188, 188, 188));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PATIENT INFORMATION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Already registered? Provide SSN :");

        txtPatientSSN.setBackground(new java.awt.Color(22, 27, 34));
        txtPatientSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPatientSSN.setForeground(new java.awt.Color(188, 188, 188));

        txtPatientIdentifier.setBackground(new java.awt.Color(22, 27, 34));
        txtPatientIdentifier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPatientIdentifier.setForeground(new java.awt.Color(188, 188, 188));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Patient ID / Visit ID : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("First Name : ");

        txtFirstName.setBackground(new java.awt.Color(22, 27, 34));
        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(188, 188, 188));

        txtHomePhone.setBackground(new java.awt.Color(22, 27, 34));
        txtHomePhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHomePhone.setForeground(new java.awt.Color(188, 188, 188));
        txtHomePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomePhoneActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(188, 188, 188));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Phone Number :");

        txtAddress.setBackground(new java.awt.Color(22, 27, 34));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(188, 188, 188));
        txtAddress.setLineWrap(true);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(188, 188, 188));
        jLabel10.setText("Last Name : ");

        txtLastName.setBackground(new java.awt.Color(22, 27, 34));
        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(188, 188, 188));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(188, 188, 188));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("SSN :");

        txtSSN.setBackground(new java.awt.Color(22, 27, 34));
        txtSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSSN.setForeground(new java.awt.Color(188, 188, 188));

        txtAge.setBackground(new java.awt.Color(22, 27, 34));
        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(188, 188, 188));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(188, 188, 188));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Age :");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(188, 188, 188));
        jLabel25.setText("Sex :");

        buttonGroup2.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnMale.setForeground(new java.awt.Color(188, 188, 188));
        radioBtnMale.setText("M");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnFemale.setForeground(new java.awt.Color(188, 188, 188));
        radioBtnFemale.setText("F");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioBtnOther);
        radioBtnOther.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnOther.setForeground(new java.awt.Color(188, 188, 188));
        radioBtnOther.setText("Other");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(188, 188, 188));
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtEmail.setText("Patient Email : ");

        txtPatientEmail.setBackground(new java.awt.Color(22, 27, 34));
        txtPatientEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPatientEmail.setForeground(new java.awt.Color(188, 188, 188));
        txtPatientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientEmailActionPerformed(evt);
            }
        });

        btnFindPatient.setBackground(new java.awt.Color(22, 27, 34));
        btnFindPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnFindPatient.setText("Find Patient");
        btnFindPatient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnFindPatientFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnFindPatientFocusLost(evt);
            }
        });
        btnFindPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindPatientMouseExited(evt);
            }
        });
        btnFindPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPatientActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(188, 188, 188));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Address : ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(txtPatientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel25)
                        .addGap(15, 15, 15)
                        .addComponent(radioBtnMale)
                        .addGap(14, 14, 14)
                        .addComponent(radioBtnFemale)
                        .addGap(11, 11, 11)
                        .addComponent(radioBtnOther))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPatientSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPatientIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnMale)
                                    .addComponent(radioBtnFemale)
                                    .addComponent(radioBtnOther))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, txtPatientSSN});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel16, jLabel17, jLabel18, jLabel24, jLabel25, jLabel4, jLabel7, txtEmail, txtPatientIdentifier});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 420, 550));

        jPanel2.setBackground(new java.awt.Color(22, 27, 34));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(188, 188, 188));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("INSURANCE INFORMATION");

        buttonGroup1.add(radioBtnPatientInsuranceYes);
        radioBtnPatientInsuranceYes.setForeground(new java.awt.Color(188, 188, 188));
        radioBtnPatientInsuranceYes.setText("Yes");
        radioBtnPatientInsuranceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnPatientInsuranceNo);
        radioBtnPatientInsuranceNo.setForeground(new java.awt.Color(188, 188, 188));
        radioBtnPatientInsuranceNo.setText("No");
        radioBtnPatientInsuranceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPatientInsuranceNoActionPerformed(evt);
            }
        });

        lblHavePolicy.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblHavePolicy.setForeground(new java.awt.Color(188, 188, 188));
        lblHavePolicy.setText("Is this patient covered by Insurance :");

        lblPolicyName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPolicyName.setForeground(new java.awt.Color(188, 188, 188));
        lblPolicyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPolicyName.setText("Policy Name :");

        lblInsCompany.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblInsCompany.setForeground(new java.awt.Color(188, 188, 188));
        lblInsCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsCompany.setText("Insurance Company :");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(188, 188, 188));
        jLabel34.setText("Reason for Visit:");

        txtReasonForVisit.setBackground(new java.awt.Color(22, 27, 34));
        txtReasonForVisit.setForeground(new java.awt.Color(188, 188, 188));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(188, 188, 188));
        jLabel11.setText("PATIENT MEDICAL CONDITION");

        lblPolicyNum.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblPolicyNum.setForeground(new java.awt.Color(188, 188, 188));
        lblPolicyNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPolicyNum.setText("Provide Insurance Policy Number :");

        txtPolicyNum.setBackground(new java.awt.Color(22, 27, 34));
        txtPolicyNum.setForeground(new java.awt.Color(188, 188, 188));
        txtPolicyNum.setEnabled(false);

        txtInsuranceCompany.setBackground(new java.awt.Color(22, 27, 34));
        txtInsuranceCompany.setForeground(new java.awt.Color(188, 188, 188));

        txtPolicyName.setBackground(new java.awt.Color(22, 27, 34));
        txtPolicyName.setForeground(new java.awt.Color(188, 188, 188));

        lblCoverage.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblCoverage.setForeground(new java.awt.Color(188, 188, 188));
        lblCoverage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCoverage.setText("Patient Insurance Coverage % :");

        txtCoverage.setBackground(new java.awt.Color(22, 27, 34));
        txtCoverage.setForeground(new java.awt.Color(188, 188, 188));

        btnResetPolicyNum.setBackground(new java.awt.Color(22, 27, 34));
        btnResetPolicyNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnResetPolicyNum.setForeground(new java.awt.Color(188, 188, 188));
        btnResetPolicyNum.setText("Reset Policy Number");
        btnResetPolicyNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnResetPolicyNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnResetPolicyNumFocusLost(evt);
            }
        });
        btnResetPolicyNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetPolicyNumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetPolicyNumMouseExited(evt);
            }
        });
        btnResetPolicyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPolicyNumActionPerformed(evt);
            }
        });

        btnFindInsurance.setBackground(new java.awt.Color(22, 27, 34));
        btnFindInsurance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindInsurance.setForeground(new java.awt.Color(188, 188, 188));
        btnFindInsurance.setText("Find Policy");
        btnFindInsurance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnFindInsuranceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnFindInsuranceFocusLost(evt);
            }
        });
        btnFindInsurance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindInsuranceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindInsuranceMouseExited(evt);
            }
        });
        btnFindInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindInsuranceActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(22, 27, 34));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(188, 188, 188));
        btnCreate.setText("Create");
        btnCreate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCreateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCreateFocusLost(evt);
            }
        });
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateMouseExited(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblInsCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel34)
                        .addGap(8, 8, 8)
                        .addComponent(txtReasonForVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblPolicyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHavePolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioBtnPatientInsuranceYes)
                                .addGap(9, 9, 9)
                                .addComponent(radioBtnPatientInsuranceNo))
                            .addComponent(txtPolicyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnResetPolicyNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHavePolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnPatientInsuranceYes)
                    .addComponent(radioBtnPatientInsuranceNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindInsurance)
                    .addComponent(btnResetPolicyNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolicyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInsCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInsuranceCompany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCoverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCoverage))
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtReasonForVisit))
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel34, lblCoverage, lblHavePolicy, lblInsCompany, lblPolicyName, lblPolicyNum, radioBtnPatientInsuranceNo, radioBtnPatientInsuranceYes});

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 420, 550));

        backJButton.setBackground(new java.awt.Color(13, 17, 23));
        backJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(188, 188, 188));
        backJButton.setText("Back");
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backJButtonMouseExited(evt);
            }
        });
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREATE APPOINTMENT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, 380, -1));

        jPanel3.setBackground(new java.awt.Color(22, 27, 34));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 20, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePhoneActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void radioBtnPatientInsuranceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceYesActionPerformed
        lblPolicyNum.setEnabled(true);
        btnFindInsurance.setEnabled(true);
        txtPolicyNum.setEnabled(true);

    }//GEN-LAST:event_radioBtnPatientInsuranceYesActionPerformed

    private void radioBtnPatientInsuranceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPatientInsuranceNoActionPerformed

        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);

        txtCoverage.setEnabled(false);

        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);

        lblPolicyName.setEnabled(false);
    }//GEN-LAST:event_radioBtnPatientInsuranceNoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        if (txtFirstName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "First name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtLastName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Last name cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (buttonGroup2.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Select gender", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtHomePhone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter phone number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtSSN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "SSN cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter age", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter address", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Please choose if patient covered by Insurance", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtReasonForVisit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please specify reason for visit", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        if (txtPatientEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email ID cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        if (!usernamePatternCorrect(txtPatientEmail.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Please provide a valid email ID in the format abc@xx.com", "Error", JOptionPane.ERROR_MESSAGE);

        } else {

            String registrationDate = txtDate.getText().trim();

            String firstName = txtFirstName.getText().trim();
            String lastName = txtLastName.getText().trim();
            String gender = "Male";
            if (radioBtnFemale.isSelected()) {
                gender = "Female";
            } else if (radioBtnOther.isSelected()) {
                gender = "Other";
            }

            String phoneNo = txtHomePhone.getText().trim();

            if (!phonePatternCorrect()) {
                JOptionPane.showMessageDialog(null, "Phone number format is invalid", "Error", JOptionPane.ERROR_MESSAGE);
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (phonePatternCorrect()) {
                txtHomePhone.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String ssn = txtSSN.getText().trim();

            if (!ssnPatternCheck()) {
                JOptionPane.showMessageDialog(null, "SSN format is invalid", "Error", JOptionPane.ERROR_MESSAGE);
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.RED));

                return;
            }

            if (ssnPatternCheck()) {
                txtSSN.setBorder(BorderFactory.createLineBorder(Color.GRAY));

            }

            String age = txtAge.getText().trim();

            try {
                Integer.parseInt(age);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Age has to numeric", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String address = txtAddress.getText().trim();
            boolean hasInsurance = false;

            String policyNumber = txtPolicyNum.getText().trim();
            if (radioBtnPatientInsuranceYes.isSelected()) {
                if (policyNumber.equals("")) {
                    JOptionPane.showMessageDialog(null, "Provide policy number", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (txtPolicyName.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "No Policy found, provide correct policy number", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            String insuranceCompany = String.valueOf(txtInsuranceCompany.getText());
            String policyName = String.valueOf(txtPolicyName.getText());
            String coverString = txtCoverage.getText().trim();
            double coverage = coverString.equals("") ? 0 : Double.parseDouble(txtCoverage.getText().trim());

            String reasonForVisit = txtReasonForVisit.getText().trim();

            if (hasInsurance) {
                if (txtPolicyNum.getText().equals("")) {
                    return;
                }
            }

            Insurance insurance = new Insurance(policyName, insuranceCompany, coverage);
            InsuranceCustomer insuranceCustomer = new InsuranceCustomer(insurance, policyNumber);

            HealthCenterEnterprise healthCenterEnterprise = (HealthCenterEnterprise) enterprise;
            Patient patient = new Patient();

            patient.setAppointmentDate(txtDate.getText());
            patient.setPatientId(patientId);
            patient.setPatientFirstName(firstName);
            patient.setPatientLastName(lastName);
            patient.setPatientGender(gender);
            patient.setPatientEmail(txtPatientEmail.getText().trim());

            patient.setContactNumber(phoneNo);
            patient.setPatientAge(age);
            patient.setPatientSSN(ssn);
            patient.setPatientAddress(address);

            patient.setInsuranceCustomer(insuranceCustomer);

            healthCenterEnterprise.getPatientDirectory().getPatients().add(patient);

            PatientTreatmentWorkRequest patientTreatmentWorkRequest = new PatientTreatmentWorkRequest(registrationDate, reasonForVisit, patient);
            patientTreatmentWorkRequest.setStatus("Waiting for Doctor");
            //   patientTreatmentWorkRequest.setSender(userAccount);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
                if (organization instanceof DoctorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
                refresh();
                JOptionPane.showMessageDialog(null, "Patient Registered Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                userProcessContainer.remove(this);
                Component[] componentArray = userProcessContainer.getComponents();
                Component component = componentArray[componentArray.length - 1];
                AccountantWorkAreaJPanel awjp = (AccountantWorkAreaJPanel) component;
                awjp.populateAllPatientsTable();
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
            }

        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnFindPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPatientActionPerformed

        boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<HealthcareNetwork> networks = ecosystem.getNetworks();
        List<HealthCenterEnterprise> healthCenterEnterprises = new ArrayList<>();

        for (HealthcareNetwork network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCenterEnterprise) {
                    healthCenterEnterprises.add((HealthCenterEnterprise) enterprise);
                }
            }
        }

        for (HealthCenterEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<Patient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (Patient patient : patients) {
                if (ssn.equals(patient.getPatientSSN())) {
                    autopopulateFields(patient);
                    isPatientFound = true;
                }

            }
        }

        if (!isPatientFound) {
            JOptionPane.showMessageDialog(null, "No patient Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFindPatientActionPerformed

    private void btnFindInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindInsuranceActionPerformed
        String insurancePolicyNumber = txtPolicyNum.getText().trim();
        String ssn = txtSSN.getText().trim();
        List<InsuranceEnterprise> insuranceEnterprises = new ArrayList<>();
        InsuranceCustomer matchedCustomer = null;

        List<HealthcareNetwork> networks = ecosystem.getNetworks();
        for (HealthcareNetwork network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof InsuranceEnterprise) {
                    insuranceEnterprises.add((InsuranceEnterprise) enterprise);
                }
            }
        }

        for (InsuranceEnterprise insuranceCompanyEnterprise : insuranceEnterprises) {
            List<InsuranceCustomer> insuranceCustomers = insuranceCompanyEnterprise.getInsuranceCustomerDirectory().getInsuranceCustomers();
            for (InsuranceCustomer insuranceCustomer : insuranceCustomers) {
                if (insurancePolicyNumber.equals(insuranceCustomer.getInsurancePolicyNumber()) && ssn.equals(insuranceCustomer.getCustSSN())) {
                    matchedCustomer = insuranceCustomer;

                }
            }
        }

        if (matchedCustomer != null) {
            txtInsuranceCompany.setText(matchedCustomer.getInsurance().getIncCompany());
            txtPolicyName.setText(matchedCustomer.getInsurance().getPolicyName());
            //  txtPolicyNo.setText(matchedCustomer.getInsurancePolicyNumber());
            txtCoverage.setText(String.valueOf(matchedCustomer.getInsurance().getCoverage()));
            txtPolicyNum.setEnabled(false);
            txtSSN.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Policy number does not match with provided SSN", "Error", JOptionPane.ERROR_MESSAGE);
            txtInsuranceCompany.setText("");
            txtPolicyName.setText("");
            txtCoverage.setText("");
            txtPolicyNum.setText("");
            return;
        }
    }//GEN-LAST:event_btnFindInsuranceActionPerformed

    private void btnResetPolicyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPolicyNumActionPerformed
        txtPolicyNum.setEnabled(true);
        txtSSN.setEnabled(true);
        txtPolicyNum.setText("");
        txtPolicyName.setText("");
        txtInsuranceCompany.setText("");
        txtCoverage.setText("");
    }//GEN-LAST:event_btnResetPolicyNumActionPerformed

    private void backJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseEntered
        // TODO add your handling code here:
        backJButton.setForeground(new Color(0,0,0));
        backJButton.setBackground(new Color(144,202,249));
    }//GEN-LAST:event_backJButtonMouseEntered

    private void backJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseExited
        // TODO add your handling code here:
        backJButton.setForeground(new Color(188,188,188));
        backJButton.setBackground(new Color(13,17,23));
    }//GEN-LAST:event_backJButtonMouseExited

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AccountantWorkAreaJPanel awjp = (AccountantWorkAreaJPanel) component;
        awjp.populateAllPatientsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnFindPatientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFindPatientFocusGained
        // TODO add your handling code here:
        btnFindPatient.setForeground(new Color(255, 255, 255));
        btnFindPatient.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnFindPatientFocusGained

    private void btnFindPatientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFindPatientFocusLost
        // TODO add your handling code here:
         btnFindPatient.setForeground(new Color(188, 188, 188));
        btnFindPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnFindPatientFocusLost

    private void btnFindPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindPatientMouseEntered
        // TODO add your handling code here:
         btnFindPatient.setForeground(new Color(255, 255, 255));
        btnFindPatient.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnFindPatientMouseEntered

    private void btnFindPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindPatientMouseExited
        // TODO add your handling code here:
        btnFindPatient.setForeground(new Color(188, 188, 188));
        btnFindPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnFindPatientMouseExited

    private void btnResetPolicyNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnResetPolicyNumFocusGained
        // TODO add your handling code here:
        btnResetPolicyNum.setForeground(new Color(255, 255, 255));
        btnResetPolicyNum.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnResetPolicyNumFocusGained

    private void btnResetPolicyNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnResetPolicyNumFocusLost
        // TODO add your handling code here:
         btnResetPolicyNum.setForeground(new Color(188, 188, 188));
        btnResetPolicyNum.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnResetPolicyNumFocusLost

    private void btnResetPolicyNumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPolicyNumMouseEntered
        // TODO add your handling code here:
         btnResetPolicyNum.setForeground(new Color(255, 255, 255));
        btnResetPolicyNum.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnResetPolicyNumMouseEntered

    private void btnResetPolicyNumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPolicyNumMouseExited
        // TODO add your handling code here:
         btnResetPolicyNum.setForeground(new Color(188, 188, 188));
        btnResetPolicyNum.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnResetPolicyNumMouseExited

    private void btnFindInsuranceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFindInsuranceFocusGained
        // TODO add your handling code here:
        btnFindInsurance.setForeground(new Color(255, 255, 255));
        btnFindInsurance.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnFindInsuranceFocusGained

    private void btnFindInsuranceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFindInsuranceFocusLost
        // TODO add your handling code here:
        btnFindInsurance.setForeground(new Color(188, 188, 188));
        btnFindInsurance.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnFindInsuranceFocusLost

    private void btnFindInsuranceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindInsuranceMouseEntered
        // TODO add your handling code here:
        btnFindInsurance.setForeground(new Color(255, 255, 255));
        btnFindInsurance.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnFindInsuranceMouseEntered

    private void btnFindInsuranceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindInsuranceMouseExited
        // TODO add your handling code here:
        btnFindInsurance.setForeground(new Color(188, 188, 188));
        btnFindInsurance.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnFindInsuranceMouseExited

    private void btnCreateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreateFocusGained
        // TODO add your handling code here:
        btnCreate.setForeground(new Color(255, 255, 255));
        btnCreate.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreateFocusGained

    private void btnCreateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreateFocusLost
        // TODO add your handling code here:
        btnCreate.setForeground(new Color(188, 188, 188));
        btnCreate.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreateFocusLost

    private void btnCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseEntered
        // TODO add your handling code here:
        btnCreate.setForeground(new Color(255, 255, 255));
        btnCreate.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreateMouseEntered

    private void btnCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseExited
        // TODO add your handling code here:
        btnCreate.setForeground(new Color(188, 188, 188));
        btnCreate.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreateMouseExited

    private void txtPatientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientEmailActionPerformed
    
                                            

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFindInsurance;
    private javax.swing.JButton btnFindPatient;
    private javax.swing.JButton btnResetPolicyNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblHavePolicy;
    private javax.swing.JLabel lblInsCompany;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNum;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JRadioButton radioBtnOther;
    private javax.swing.JRadioButton radioBtnPatientInsuranceNo;
    private javax.swing.JRadioButton radioBtnPatientInsuranceYes;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtInsuranceCompany;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientId11;
    private javax.swing.JTextField txtPatientIdentifier;
    private javax.swing.JTextField txtPatientSSN;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyNum;
    private javax.swing.JTextField txtReasonForVisit;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

    private void populateField() {
        LocalDateTime localTimeUpdate = LocalDateTime.now();
        DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern("MM/dd/yyyy hh:mm:ss");
        txtDate.setText(localTimeUpdate.format(dateTimeFormat));

        txtPatientIdentifier.setText(patientId);

        lblPolicyNum.setEnabled(false);
        btnFindInsurance.setEnabled(false);
        txtPolicyNum.setEnabled(false);
        txtInsuranceCompany.setEnabled(false);
        txtPolicyName.setEnabled(false);

        txtCoverage.setEnabled(false);

        lblCoverage.setEnabled(false);
        lblInsCompany.setEnabled(false);

        lblPolicyName.setEnabled(false);
    }

    private void refresh() {

        txtPatientIdentifier.setText(UUID.randomUUID().toString().substring(0, 7));
        txtFirstName.setText("");
        txtLastName.setText("");
        txtHomePhone.setText("");
        txtAge.setText("");
        txtSSN.setText("");
        txtAddress.setText("");
        txtReasonForVisit.setText("");
        txtPatientEmail.setText("");
        txtPolicyName.setText("");
        txtPolicyNum.setText("");
        txtCoverage.setText("");
        txtInsuranceCompany.setText("");
    }

    private boolean phonePatternCorrect() {

        Pattern pattern = Pattern.compile("\\d{10}|(?:\\d{3}-){2}\\d{4}|\\(\\d{3}\\)\\d{3}-?\\d{4}");
        Matcher matcher = pattern.matcher(txtHomePhone.getText());

        boolean b = false;

        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }

        return b;
    }

    private boolean ssnPatternCheck() {

        Pattern pattern = Pattern.compile("^\\d{9}$");
        Matcher matcher = pattern.matcher(txtSSN.getText());

        boolean b = false;

        if (matcher.matches()) {
            b = true;
        } else {
            b = false;
        }

        return b;
    }

    private void autopopulateFields(Patient patient) {
        txtFirstName.setText(patient.getPatientFirstName());
        txtLastName.setText(patient.getPatientLastName());
        txtPatientIdentifier.setText(patient.getPatientId());
        txtHomePhone.setText(patient.getContactNumber());
        txtSSN.setText(patient.getPatientSSN());
        txtAge.setText(patient.getPatientAge());
        txtAddress.setText(patient.getPatientAddress());
        txtPatientEmail.setText(patient.getPatientEmail());

        String sex = patient.getPatientGender();

        if (sex.equals("Male")) {
            radioBtnMale.setSelected(true);
        } else if (sex.equals("Female")) {
            radioBtnFemale.setSelected(true);
        } else if (sex.equals("Other")) {
            radioBtnOther.setSelected(true);
        }

    }

    private boolean usernamePatternCorrect(String username) {
        Pattern p = Pattern.compile("^(.+)@(.+)$");
        Matcher m = p.matcher(username);
        boolean b = m.matches();
        return b;

    }

    private boolean checkEmailDuplication(String patientEmail) {
        boolean isPatientFound = false;
        String ssn = txtPatientSSN.getText().trim();
        List<HealthcareNetwork> networks = ecosystem.getNetworks();
        List<HealthCenterEnterprise> healthCenterEnterprises = new ArrayList<>();

        for (HealthcareNetwork network : networks) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthCenterEnterprise) {
                    healthCenterEnterprises.add((HealthCenterEnterprise) enterprise);
                }
            }
        }

        for (HealthCenterEnterprise healthCenterEnterprise : healthCenterEnterprises) {
            List<Patient> patients = healthCenterEnterprise.getPatientDirectory().getPatients();
            for (Patient patient : patients) {
                if (patientEmail.equals(patient.getPatientEmail())) {
                    isPatientFound = true;
                    break;
                }

            }
        }
        return isPatientFound;
    }
}
