/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalAccountantRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sai Dutt & Ganesh
 */
public class EmailBillingInformationToPatient extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AccountantBillingRequest accountBillingRequest;
    private String amount;
    private UserAccount userAccount;
    private Enterprise enterprise;

    public EmailBillingInformationToPatient(JPanel userProcessContainer, AccountantBillingRequest accountBillingRequest, String amount, UserAccount ua, Enterprise e) {
        initComponents();
        
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Email lady.gif"));
        icon.getImage().flush();
        jLabel1.setIcon(icon);
        
        this.userProcessContainer = userProcessContainer;
        this.accountBillingRequest = accountBillingRequest;
        this.amount = amount;
        this.userAccount = ua;
        this.enterprise = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emailTxtFiled = new javax.swing.JTextArea();
        btnSendEmail = new javax.swing.JButton();
        btnClearText = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 17, 23));
        setPreferredSize(new java.awt.Dimension(1200, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailTxtFiled.setBackground(new java.awt.Color(22, 27, 34));
        emailTxtFiled.setColumns(20);
        emailTxtFiled.setForeground(new java.awt.Color(188, 188, 188));
        emailTxtFiled.setRows(5);
        jScrollPane1.setViewportView(emailTxtFiled);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 600, 260));

        btnSendEmail.setBackground(new java.awt.Color(22, 27, 34));
        btnSendEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSendEmail.setForeground(new java.awt.Color(188, 188, 188));
        btnSendEmail.setText("Send Email");
        btnSendEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSendEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSendEmailFocusLost(evt);
            }
        });
        btnSendEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSendEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSendEmailMouseExited(evt);
            }
        });
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });
        add(btnSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, 37));

        btnClearText.setBackground(new java.awt.Color(22, 27, 34));
        btnClearText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClearText.setForeground(new java.awt.Color(188, 188, 188));
        btnClearText.setText("Clear");
        btnClearText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnClearTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnClearTextFocusLost(evt);
            }
        });
        btnClearText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearTextMouseExited(evt);
            }
        });
        btnClearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTextActionPerformed(evt);
            }
        });
        add(btnClearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 93, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMAIL BILLING INFO TO PATIENT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, 380, -1));

        backJButton.setBackground(new java.awt.Color(13, 17, 23));
        backJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(188, 188, 188));
        backJButton.setText("Back");
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backJButtonMouseExited(evt);
            }
        });
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Email lady.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        String text = emailTxtFiled.getText();
        if (emailTxtFiled.getText().trim().equals("")) {
            JOptionPane.showConfirmDialog(null, "Enter a message", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SendMail(accountBillingRequest.getPatient().getPatientEmail(), text);
        JOptionPane.showMessageDialog(null, "Billing information sent to " + accountBillingRequest.getPatient().getPatientFirstName(), "Success", JOptionPane.INFORMATION_MESSAGE);
        accountBillingRequest.setStatus("Patient Transaction Completed");
        
        jLabel1.setIcon(null);
        jLabel1.revalidate();
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 2];
        ProcessMedicalBillingsJPanel awjp = (ProcessMedicalBillingsJPanel) component;
        awjp.populateTable();
        awjp.populateInsuranceClaimTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void btnClearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTextActionPerformed
        emailTxtFiled.setText("");
    }//GEN-LAST:event_btnClearTextActionPerformed

    private void backJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseEntered
        // TODO add your handling code here:
        backJButton.setForeground(new Color(0, 0, 0));
        backJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_backJButtonMouseEntered

    private void backJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseExited
        // TODO add your handling code here:
        backJButton.setForeground(new Color(188, 188, 188));
        backJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_backJButtonMouseExited

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSendEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSendEmailFocusGained
        // TODO add your handling code here:
        btnSendEmail.setForeground(new Color(255, 255, 255));
        btnSendEmail.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnSendEmailFocusGained

    private void btnSendEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSendEmailFocusLost
        // TODO add your handling code here:
        btnSendEmail.setForeground(new Color(188, 188, 188));
        btnSendEmail.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnSendEmailFocusLost

    private void btnSendEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendEmailMouseEntered
        // TODO add your handling code here:
        btnSendEmail.setForeground(new Color(255, 255, 255));
        btnSendEmail.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnSendEmailMouseEntered

    private void btnSendEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendEmailMouseExited
        // TODO add your handling code here:
        btnSendEmail.setForeground(new Color(188, 188, 188));
        btnSendEmail.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnSendEmailMouseExited

    private void btnClearTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClearTextFocusGained
        // TODO add your handling code here:
        btnClearText.setForeground(new Color(255, 255, 255));
        btnClearText.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnClearTextFocusGained

    private void btnClearTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClearTextFocusLost
        // TODO add your handling code here:
        btnClearText.setForeground(new Color(188, 188, 188));
        btnClearText.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnClearTextFocusLost

    private void btnClearTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearTextMouseEntered
        // TODO add your handling code here:
        btnClearText.setForeground(new Color(255, 255, 255));
        btnClearText.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnClearTextMouseEntered

    private void btnClearTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearTextMouseExited
        // TODO add your handling code here:
        btnClearText.setForeground(new Color(188, 188, 188));
        btnClearText.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnClearTextMouseExited

    private void SendMail(String toMail, String text) {

        final String username = "aedprojectak@outlook.com";
        final String password = "Kamshetty707$";
        Properties props = new Properties();
       
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "outlook.office365.com");
        props.put("mail.smtp.port", "587");
       
        Session session = Session.getInstance(props,
          new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
          });

        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress("aedprojectak@outlook.com"));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toMail));
            message.setSubject("Patient Billing Information");

            message.setContent("<img src=\"http://aquariusmedical.ca/wp-content/themes/aquarius/img/inner-banner1.png\" style=\"width:950px;height:200px;\"><h1><right>" + enterprise.getName() + "</right></h1>"
                    + "<p>Dear " + accountBillingRequest.getPatient().getPatientFirstName() + ",</p>"
                    + "<p>Your treatment was completed. Please find below the final billing details:</p>"
                    + "<p>Total Payable Amount" + "        : $" + amount + "</p>"
                    + "<p>" + emailTxtFiled.getText() + "</p>"
                    + "<p>Regards,</p>"
                    + "<p>" + userAccount.getEmp().getEmpName() + "</p><br/>", "text/html");

            Transport.send(message);
        } catch (MessagingException e) {
          throw new RuntimeException(e);
           
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnClearText;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JTextArea emailTxtFiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
