/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.HealthcareNetwork;
import model.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Sai Dutt
 */
public class LoginJPanel extends javax.swing.JPanel {

    private JPanel container;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;

    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(EcoSystem ecosystem, DB4OUtil dB4OUtil,JPanel container) {
        initComponents();
        
        this.ecosystem = ecosystem;
        this.dB4OUtil = dB4OUtil;
        this.container=container;
        
        setupLogin();
    }
    
    public void setupLogin() {
        
        btnLogin.setEnabled(true);
        fldUserName.setEnabled(true);
        fldPassword.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        fldPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 17, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 27, 34));
        jPanel1.setForeground(new java.awt.Color(188, 188, 188));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Username");

        fldUserName.setBackground(new java.awt.Color(22, 27, 34));
        fldUserName.setForeground(new java.awt.Color(188, 188, 188));
        fldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldUserNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setText("Password");

        btnLogin.setBackground(new java.awt.Color(22, 27, 34));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(188, 188, 188));
        btnLogin.setText("Login");
        btnLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnLoginFocusLost(evt);
            }
        });
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        fldPassword.setBackground(new java.awt.Color(22, 27, 34));
        fldPassword.setForeground(new java.awt.Color(188, 188, 188));
        fldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldPasswordActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(22, 27, 34));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("You will be redirected to your ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 223, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(188, 188, 188));
        jLabel6.setText("Enter credentials to login.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 223, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(188, 188, 188));
        jLabel7.setText("respective work area after login.");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 223, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(fldUserName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldPassword)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogin)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fldPassword, fldUserName});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 102, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/loginphoto.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 380, 760));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/loginphoto.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 880, 760));

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel10.setText("madgi");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 50, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void fldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldUserNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String username = fldUserName.getText();
        char[] pwdArray = fldPassword.getPassword();
        String password = String.valueOf(pwdArray);

        UserAccount ua = ecosystem.getUserDirectory().authenticateUser(username, password);

        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        HealthcareNetwork net=null;

        if (ua == null) {
            
            for (HealthcareNetwork network : ecosystem.getNetworks()) {
                
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    
                    ua = enterprise.getUserDirectory().authenticateUser(username, password);
                    
                    if (ua == null) {
                        
                        for (Organization o : enterprise.getOrganizationDirectory().getOrganizations()) {
                            
                            ua = o.getUserDirectory().authenticateUser(username, password);
                            
                            if (ua != null) {
                                
                                net=network;
                                inEnterprise = enterprise;
                                inOrganization = o;
                                break;
                            }
                        }

                    } else {
                        
                        inEnterprise = enterprise;
                        break;
                    }
                    
                    if (inOrganization != null) {
                        
                        break;
                    }
                }
                
                if (inEnterprise != null) {
                    
                    break;
                }
            }
        }

        if (ua == null) {
            
            fldUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            fldPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
            
        } else {
            
            fldUserName.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            fldPassword.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", ua.getRole().createWorkArea(container, ua, inOrganization, inEnterprise, ecosystem, dB4OUtil));
            layout.next(container);
        }

        btnLogin.setEnabled(false);
        fldUserName.setEnabled(false);
        fldPassword.setEnabled(false);

    }//GEN-LAST:event_btnLoginActionPerformed

    private void fldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPasswordActionPerformed

    private void mouseHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseHover
        // TODO add your handling code here:
        
        btnLogin.setForeground(new Color(255,255,255));
        btnLogin.setBackground(new Color(35,134,54));
        
    }//GEN-LAST:event_mouseHover

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        
        btnLogin.setForeground(new Color(188,188,188));
        btnLogin.setBackground(new Color(22,27,34));
        
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnLoginFocusGained
        // TODO add your handling code here:
        btnLogin.setForeground(new Color(255,255,255));
        btnLogin.setBackground(new Color(35,134,54));
    }//GEN-LAST:event_btnLoginFocusGained

    private void btnLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnLoginFocusLost
        // TODO add your handling code here:
        btnLogin.setForeground(new Color(188,188,188));
        btnLogin.setBackground(new Color(22,27,34));
    }//GEN-LAST:event_btnLoginFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JTextField fldUserName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
