/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Employee.Employee;
import model.Enterprise.*;
import model.Network.HealthcareNetwork;
import model.Role.EnterpriseAdminRole;
import model.Role.Role;
import model.UserAccount.UserAccount;
import model.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.LoginJPanel;
import userinterface.MedicalAccountantRole.EmailBillingInformationToPatient;

/**
 *
 * @author Sai Dutt & Ganesh
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private Employee employee;
    private UserAccountDirectory userAccountDirectory;
    DB4OUtil dB4OUtil;

    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil dB4OUtil) {
        
        initComponents();
        usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        reEnterPasswordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        nameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        this.userProcessContainer = userProcessContainer;
        this.system = system;      
        this.dB4OUtil=dB4OUtil;   
        
        populateEnterpriseComboBox(this.system.searchNetwork("System"));
        populateTable();        
    }

    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (HealthcareNetwork network : system.getNetworks()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();                    
                    row[1] = userAccount.getUserName();
                    row[2] = enterprise.getEnterpriseType().getValue();

                    model.addRow(row);
                }
                TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
                enterpriseJTable.setRowSorter(sorter);
            }
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        enterpriseJTable.setRowSorter(sorter);
    }    

    private void populateEnterpriseComboBox(HealthcareNetwork network) {
        
        enterpriseJComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseJComboBox.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        usernameJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        passwordJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        rePasswordJLabel = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        reEnterPasswordJPasswordField = new javax.swing.JPasswordField();
        passwordJPasswordField = new javax.swing.JPasswordField();
        deleteEnterpriseJButton = new javax.swing.JButton();
        updateEnterpriseJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLogoutPatient = new javax.swing.JButton();

        setBackground(new java.awt.Color(13, 17, 23));
        setPreferredSize(new java.awt.Dimension(1200, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setBackground(new java.awt.Color(13, 17, 23));
        enterpriseJTable.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Username", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterpriseJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 78, 1140, 120));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(188, 188, 188));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("MANAGE ENTERPRISE ADMIN");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, 380, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(188, 188, 188));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<> with ♡ by Team Batman");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 705, 282, -1));

        jPanel1.setBackground(new java.awt.Color(22, 27, 34));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(188, 188, 188));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ENTERPRISE ADMIN");

        usernameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameJLabel.setForeground(new java.awt.Color(188, 188, 188));
        usernameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameJLabel.setText("Username :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Enterprise :");

        enterpriseJComboBox.setBackground(new java.awt.Color(22, 27, 34));
        enterpriseJComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterpriseJComboBox.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitJButton.setBackground(new java.awt.Color(22, 27, 34));
        submitJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(188, 188, 188));
        submitJButton.setText("Submit");
        submitJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                submitJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                submitJButtonFocusLost(evt);
            }
        });
        submitJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitJButtonMouseExited(evt);
            }
        });
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        passwordJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordJLabel.setForeground(new java.awt.Color(188, 188, 188));
        passwordJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordJLabel.setText("Password :");

        nameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameJLabel.setForeground(new java.awt.Color(188, 188, 188));
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameJLabel.setText("Name :");

        rePasswordJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rePasswordJLabel.setForeground(new java.awt.Color(188, 188, 188));
        rePasswordJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rePasswordJLabel.setText("Confirm Password :");

        usernameJTextField.setBackground(new java.awt.Color(22, 27, 34));
        usernameJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameJTextField.setForeground(new java.awt.Color(188, 188, 188));
        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });

        nameJTextField.setBackground(new java.awt.Color(22, 27, 34));
        nameJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(188, 188, 188));
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });

        reEnterPasswordJPasswordField.setBackground(new java.awt.Color(22, 27, 34));
        reEnterPasswordJPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passwordJPasswordField.setBackground(new java.awt.Color(22, 27, 34));
        passwordJPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        deleteEnterpriseJButton.setBackground(new java.awt.Color(22, 27, 34));
        deleteEnterpriseJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteEnterpriseJButton.setForeground(new java.awt.Color(188, 188, 188));
        deleteEnterpriseJButton.setText("Delete");
        deleteEnterpriseJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deleteEnterpriseJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deleteEnterpriseJButtonFocusLost(evt);
            }
        });
        deleteEnterpriseJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteEnterpriseJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteEnterpriseJButtonMouseExited(evt);
            }
        });
        deleteEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnterpriseJButtonActionPerformed(evt);
            }
        });

        updateEnterpriseJButton.setBackground(new java.awt.Color(22, 27, 34));
        updateEnterpriseJButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateEnterpriseJButton.setForeground(new java.awt.Color(188, 188, 188));
        updateEnterpriseJButton.setText("Update");
        updateEnterpriseJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateEnterpriseJButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateEnterpriseJButtonFocusLost(evt);
            }
        });
        updateEnterpriseJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateEnterpriseJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateEnterpriseJButtonMouseExited(evt);
            }
        });
        updateEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnterpriseJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(rePasswordJLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJPasswordField)
                                    .addComponent(reEnterPasswordJPasswordField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJTextField)
                                    .addComponent(usernameJTextField)
                                    .addComponent(enterpriseJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(updateEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, nameJLabel, passwordJLabel, usernameJLabel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rePasswordJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reEnterPasswordJPasswordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 420, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Enterprise Admin.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 500, 470));

        btnLogoutPatient.setBackground(new java.awt.Color(13, 17, 23));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

        String username = usernameJTextField.getText();
        Role role = null;
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String rePassword = String.valueOf(reEnterPasswordJPasswordField.getPassword());
        String name = nameJTextField.getText();

        if (username == null || username.equals("")) {
            usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            usernameJLabel.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Username can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (password == null || password.equals("")) {
            usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            usernameJLabel.setForeground(Color.BLACK);
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            passwordJLabel.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Password can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!passwordPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Password should be at least 6 Characters "
                    + "digits and a combination of number , uppercase letter, "
                    + "lowercase letter and Special characters are not allowed other than $, +, _", "Error", JOptionPane.ERROR_MESSAGE);
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            passwordJLabel.setForeground(Color.RED);
            return;
        }

        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(null, "Passwords don't match", "Error", JOptionPane.ERROR_MESSAGE);
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            reEnterPasswordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
            passwordJLabel.setForeground(Color.RED);
            rePasswordJLabel.setForeground(Color.RED);
            return;
        }

        if (name == null || name.equals("")) {
            
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            reEnterPasswordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            passwordJLabel.setForeground(Color.BLACK);
            rePasswordJLabel.setForeground(Color.BLACK);
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            nameJLabel.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Name can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            
        } else {
            
            List<UserAccount> userAccountList = enterprise.getUserDirectory().getUserAccountList();
            for (UserAccount userAccount : userAccountList) {
                if (userAccount.getUserName().equals(username)) {
                    JOptionPane.showMessageDialog(null, "Username already exists", "Error", JOptionPane.ERROR_MESSAGE);
                    usernameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
                    return;
                }
            }

            Employee employee = enterprise.getEmpDirectory().createEmployee(name);
            UserAccount userAccount = enterprise.getUserDirectory().createUserAccount(username, password, employee, new EnterpriseAdminRole());
            populateTable();

            passwordJLabel.setForeground(Color.BLACK);
            rePasswordJLabel.setForeground(Color.BLACK);
            nameJLabel.setForeground(Color.BLACK);
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            passwordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            reEnterPasswordJPasswordField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            nameJTextField.setText("");
            passwordJPasswordField.setText("");
            reEnterPasswordJPasswordField.setText("");
            usernameJTextField.setText("");
        }

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:

        jLabel12.setFont(new Font(jLabel12.getFont().getName(), Font.PLAIN, 19));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:

        jLabel12.setFont(new Font(jLabel12.getFont().getName(), Font.PLAIN, 18));
    }//GEN-LAST:event_jLabel12MouseExited

    private void submitJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_submitJButtonFocusGained
        // TODO add your handling code here:
        submitJButton.setForeground(new Color(255, 255, 255));
        submitJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_submitJButtonFocusGained

    private void submitJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_submitJButtonFocusLost
        // TODO add your handling code here:
        submitJButton.setForeground(new Color(188, 188, 188));
        submitJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_submitJButtonFocusLost

    private void submitJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitJButtonMouseEntered
        // TODO add your handling code here:
        submitJButton.setForeground(new Color(255, 255, 255));
        submitJButton.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_submitJButtonMouseEntered

    private void submitJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitJButtonMouseExited
        // TODO add your handling code here:
        submitJButton.setForeground(new Color(188, 188, 188));
        submitJButton.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_submitJButtonMouseExited

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void deleteEnterpriseJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEnterpriseJButtonFocusGained

    private void deleteEnterpriseJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEnterpriseJButtonFocusLost

    private void deleteEnterpriseJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEnterpriseJButtonMouseEntered

    private void deleteEnterpriseJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEnterpriseJButtonMouseExited

    private void deleteEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnterpriseJButtonActionPerformed
                
        int row = enterpriseJTable.getSelectedRow();
        
        String username;
        String enterpriseName;
        String networkName;
        
        if (row < 0) 
            return;
        
        enterpriseName = enterpriseJTable.getValueAt(row, 0).toString();
        username = enterpriseJTable.getValueAt(row,1).toString();
        
        this.system.searchNetwork("System").getEnterpriseDirectory().searchEnterprise(enterpriseName).getUserDirectory().deleteUser(username);
        
        populateTable();

    }//GEN-LAST:event_deleteEnterpriseJButtonActionPerformed

    private void enterpriseJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterpriseJTableMouseClicked
            
    }//GEN-LAST:event_enterpriseJTableMouseClicked

    private void updateEnterpriseJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateEnterpriseJButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEnterpriseJButtonFocusGained

    private void updateEnterpriseJButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateEnterpriseJButtonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEnterpriseJButtonFocusLost

    private void updateEnterpriseJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEnterpriseJButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEnterpriseJButtonMouseEntered

    private void updateEnterpriseJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEnterpriseJButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEnterpriseJButtonMouseExited

    private void updateEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnterpriseJButtonActionPerformed
        
        int row = enterpriseJTable.getSelectedRow();
        UserAccount ua;
        
        String username;
        String enterpriseName;
        String networkName;
        
        if (row < 0) 
            return;
        
        enterpriseName = enterpriseJTable.getValueAt(row, 0).toString();
        username = enterpriseJTable.getValueAt(row,1).toString();
        
        ua = this.system.searchNetwork("System").getEnterpriseDirectory().searchEnterprise(enterpriseName).getUserDirectory().searchUser(username);
        
        JFrame regFrame = new JFrame();
        UpdateAdminDtlsJPanel panel = new UpdateAdminDtlsJPanel(ua, this);
        
        regFrame.getContentPane().add(panel);
        regFrame.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Window opens in full size mode
        regFrame.setVisible(true);                
    }//GEN-LAST:event_updateEnterpriseJButtonActionPerformed

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        userProcessContainer.removeAll();
        LoginJPanel lp = new LoginJPanel(this.system, dB4OUtil, userProcessContainer);
        userProcessContainer.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(this.system);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed
     
    
    private boolean passwordPatternCorrect() {
        Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[$+_])(?=\\S+$).{6,}$");
        Matcher m = p.matcher(String.valueOf(passwordJPasswordField.getPassword()));
        boolean b = m.matches();
        return b;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JButton deleteEnterpriseJButton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JPasswordField reEnterPasswordJPasswordField;
    private javax.swing.JLabel rePasswordJLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton updateEnterpriseJButton;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
