/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceArchitectRole;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.InsuranceEnterprise;
import model.Insurance.Insurance;
import model.Organization.InsArchitectOrganization;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.LoginJPanel;

/**
 *
 * @author Akshita
 */
public class InsuranceArchitectWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private InsArchitectOrganization insurancePolicyPlannerOrganization;
    private InsuranceEnterprise insuranceCompanyEnterprise;
    private DB4OUtil dB4OUtil;
    private EcoSystem ecosystem;

    public InsuranceArchitectWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InsArchitectOrganization insurancePolicyPlannerOrganization, Enterprise enterprise, DB4OUtil dB4OUtil, EcoSystem business) {
        initComponents();

        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Insurance.gif"));
        icon.getImage().flush();
        jLabel7.setIcon(icon);

        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.insurancePolicyPlannerOrganization = insurancePolicyPlannerOrganization;
        this.insuranceCompanyEnterprise = (InsuranceEnterprise) enterprise;
        this.dB4OUtil = dB4OUtil;
        this.ecosystem = business;
        valueLabel1.setText(enterprise.getName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnLogoutPatient = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnCreatePolicy = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        btnDeletePolicy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicies = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        txtPolicyCoverage = new javax.swing.JTextField();
        txtMonthlyPrem = new javax.swing.JTextField();
        txtPolicyTC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(188, 188, 188));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<> with ♡ by Team Batman");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        setBackground(new java.awt.Color(13, 17, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogoutPatient.setBackground(new java.awt.Color(13, 17, 23));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("INSURANCE ARCHITECT WORK AREA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 6, 410, -1));

        jPanel2.setBackground(new java.awt.Color(22, 27, 34));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(188, 188, 188));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MANAGE POLICIES");

        btnCreatePolicy.setBackground(new java.awt.Color(22, 27, 34));
        btnCreatePolicy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreatePolicy.setForeground(new java.awt.Color(188, 188, 188));
        btnCreatePolicy.setText("Create Policy");
        btnCreatePolicy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCreatePolicyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCreatePolicyFocusLost(evt);
            }
        });
        btnCreatePolicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreatePolicyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreatePolicyMouseExited(evt);
            }
        });
        btnCreatePolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePolicyActionPerformed(evt);
            }
        });

        enterpriseLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel1.setText("Enterprise :");

        valueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        valueLabel1.setForeground(new java.awt.Color(188, 188, 188));
        valueLabel1.setText("<value>");

        btnDeletePolicy.setBackground(new java.awt.Color(22, 27, 34));
        btnDeletePolicy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeletePolicy.setForeground(new java.awt.Color(188, 188, 188));
        btnDeletePolicy.setText("Delete Policy");
        btnDeletePolicy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDeletePolicyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnDeletePolicyFocusLost(evt);
            }
        });
        btnDeletePolicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletePolicyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletePolicyMouseExited(evt);
            }
        });
        btnDeletePolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePolicyActionPerformed(evt);
            }
        });

        tblPolicies.setBackground(new java.awt.Color(22, 27, 34));
        tblPolicies.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPolicies.setForeground(new java.awt.Color(188, 188, 188));
        tblPolicies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Policy Name", "Coverage(%)", "Monthly Premium($", "Policy T&C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPolicies);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(188, 188, 188));
        jLabel11.setText("Policy Name :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(188, 188, 188));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Policy Coverage(%) :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(188, 188, 188));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Monthly Premium($) :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(188, 188, 188));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Policy T&C :");

        txtPolicyName.setBackground(new java.awt.Color(22, 27, 34));
        txtPolicyName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPolicyName.setForeground(new java.awt.Color(188, 188, 188));

        txtPolicyCoverage.setBackground(new java.awt.Color(22, 27, 34));
        txtPolicyCoverage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPolicyCoverage.setForeground(new java.awt.Color(188, 188, 188));

        txtMonthlyPrem.setBackground(new java.awt.Color(22, 27, 34));
        txtMonthlyPrem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonthlyPrem.setForeground(new java.awt.Color(188, 188, 188));

        txtPolicyTC.setBackground(new java.awt.Color(22, 27, 34));
        txtPolicyTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPolicyTC.setForeground(new java.awt.Color(188, 188, 188));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(enterpriseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPolicyTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPolicyCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonthlyPrem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletePolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreatePolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel1)
                    .addComponent(valueLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPolicyCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonthlyPrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPolicyTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCreatePolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletePolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, txtMonthlyPrem, txtPolicyCoverage, txtPolicyName, txtPolicyTC});

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 420, 550));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesLatest/Insurance.gif"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:

        //jLabel3.setFont(new Font(jLabel1.getFont().getName(),Font.PLAIN,19));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:

        // jLabel3.setFont(new Font(jLabel1.getFont().getName(),Font.PLAIN,18));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:

//        jLabel10.setFont(new Font(jLabel10.getFont().getName(),Font.PLAIN,19));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:

//        jLabel10.setFont(new Font(jLabel10.getFont().getName(),Font.PLAIN,18));
    }//GEN-LAST:event_jLabel10MouseExited

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        userProcessContainer.removeAll();
        LoginJPanel lp = new LoginJPanel(ecosystem, dB4OUtil, userProcessContainer);
        userProcessContainer.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);

    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void btnCreatePolicyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreatePolicyFocusGained
        // TODO add your handling code here:
        btnCreatePolicy.setForeground(new Color(255, 255, 255));
        btnCreatePolicy.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreatePolicyFocusGained

    private void btnCreatePolicyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCreatePolicyFocusLost
        // TODO add your handling code here:
        btnCreatePolicy.setForeground(new Color(188, 188, 188));
        btnCreatePolicy.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreatePolicyFocusLost

    private void btnCreatePolicyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePolicyMouseEntered
        // TODO add your handling code here:
        btnCreatePolicy.setForeground(new Color(255, 255, 255));
        btnCreatePolicy.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCreatePolicyMouseEntered

    private void btnCreatePolicyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreatePolicyMouseExited
        // TODO add your handling code here:
        btnCreatePolicy.setForeground(new Color(188, 188, 188));
        btnCreatePolicy.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnCreatePolicyMouseExited

    private void btnCreatePolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePolicyActionPerformed

        String policyName = txtPolicyName.getText().trim();
        String poliCoverageTxt = txtPolicyCoverage.getText().trim();
        String monthlyPremiumTxt = txtMonthlyPrem.getText().trim();
        String policyTC = txtPolicyTC.getText().trim();
        if (policyName.equals("")) {
            JOptionPane.showMessageDialog(null, "Policy Name is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (poliCoverageTxt.equals("")) {
            JOptionPane.showMessageDialog(null, "Policy Coverage is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (monthlyPremiumTxt.equals("")) {
            JOptionPane.showMessageDialog(null, "Monthly Premium is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (policyTC.equals("")) {
            JOptionPane.showMessageDialog(null, "Policy TC is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double policyCoverage = 0;
        try {
            if (Double.parseDouble(poliCoverageTxt)>100) {
                JOptionPane.showMessageDialog(null, "Policy Coverage cannot be greater than 100", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            policyCoverage = Double.parseDouble(poliCoverageTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Insurance coverage should be numeric", "Error", JOptionPane.ERROR_MESSAGE);

            return;
        }

        double monthlyPremium = 0;
        try {
            monthlyPremium = Double.parseDouble(monthlyPremiumTxt);
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(null, "Monthly premium should be numeric", "Error", JOptionPane.ERROR_MESSAGE);
        }

        ArrayList<Insurance> policies = insuranceCompanyEnterprise.getInsurancePolicyDirectory().getPolicies();
        for (Insurance insurance : policies) {
            if (policyName.equalsIgnoreCase(insurance.getPolicyName())) {
                JOptionPane.showMessageDialog(null, "Policy already exists, please provide some other policy name", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Insurance insurance = new Insurance(policyName, insuranceCompanyEnterprise.getName(), policyCoverage);
        insurance.setPolicyTC(policyTC);
        insurance.setMonthlyPremium(monthlyPremium);

        insuranceCompanyEnterprise.getInsurancePolicyDirectory().getPolicies().add(insurance);
        JOptionPane.showMessageDialog(null, "Policy Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        txtPolicyName.setText("");
        txtMonthlyPrem.setText("");
        txtPolicyCoverage.setText("");
        txtPolicyTC.setText("");
    }//GEN-LAST:event_btnCreatePolicyActionPerformed

    private void btnDeletePolicyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDeletePolicyFocusGained
        // TODO add your handling code here:
        btnDeletePolicy.setForeground(new Color(255, 255, 255));
        btnDeletePolicy.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnDeletePolicyFocusGained

    private void btnDeletePolicyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDeletePolicyFocusLost
        // TODO add your handling code here:
        btnDeletePolicy.setForeground(new Color(188, 188, 188));
        btnDeletePolicy.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnDeletePolicyFocusLost

    private void btnDeletePolicyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePolicyMouseEntered
        // TODO add your handling code here:
        btnDeletePolicy.setForeground(new Color(255, 255, 255));
        btnDeletePolicy.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnDeletePolicyMouseEntered

    private void btnDeletePolicyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePolicyMouseExited
        // TODO add your handling code here:
        btnDeletePolicy.setForeground(new Color(188, 188, 188));
        btnDeletePolicy.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnDeletePolicyMouseExited

    private void btnDeletePolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePolicyActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) tblPolicies.getModel();
        int selectedRow = tblPolicies.getSelectedColumnCount();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a policy to be deleted", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            insuranceCompanyEnterprise.getInsurancePolicyDirectory().getPolicies().remove((Insurance) dtm.getValueAt(selectedRow, 0));
            JOptionPane.showMessageDialog(null, "Policy deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateTable();
        }
    }//GEN-LAST:event_btnDeletePolicyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePolicy;
    private javax.swing.JButton btnDeletePolicy;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPolicies;
    private javax.swing.JTextField txtMonthlyPrem;
    private javax.swing.JTextField txtPolicyCoverage;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txtPolicyTC;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblPolicies.getModel();
        model.setRowCount(0);
        List<Insurance> policies = insuranceCompanyEnterprise.getInsurancePolicyDirectory().getPolicies();
        for (Insurance insurancePolicy : policies) {
            Object[] row = new Object[4];
            row[0] = insurancePolicy;
            row[1] = insurancePolicy.getCoverage();
            row[2] = insurancePolicy.getMonthlyPremium();
            row[3] = insurancePolicy.getPolicyTC();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblPolicies.setRowSorter(sorter);
    }
}
