/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOTreasurerRole;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Organization.Organization;
import model.Organization.NGOTreasurerOrganization;
import model.UserAccount.UserAccount;
import model.WorkQueue.NGOFundRequest;
import model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.LoginJPanel;

/**
 *
 * @author Sai Dutt
 */
public class NGOTreasurerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOTreasurerWorkAreaJPanel
     */
    private JPanel jPanel;
    private UserAccount userAccount;
    private NGOTreasurerOrganization treasurerOrganization;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil;
    private EcoSystem ecoSystem;

    public NGOTreasurerWorkAreaJPanel(JPanel jpanel, UserAccount userAccount, Organization organization, Enterprise enterprise, DB4OUtil dB4OUtil, EcoSystem ecosystem) {
        initComponents();
        this.enterprise = enterprise;
        this.jPanel = jpanel;
        this.treasurerOrganization = (NGOTreasurerOrganization) organization;
        this.userAccount = userAccount;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem= ecosystem;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnLogoutPatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        btnAssign1 = new javax.swing.JButton();
        btnCompleteDelivery = new javax.swing.JButton();

        setBackground(new java.awt.Color(13, 17, 23));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setBackground(new java.awt.Color(13, 17, 23));
        workRequestJTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(188, 188, 188));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Status", "Amount", "Message", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 1080, 370));

        btnLogoutPatient.setBackground(new java.awt.Color(13, 17, 23));
        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setForeground(new java.awt.Color(188, 188, 188));
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TREASURER WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 6, 430, -1));

        enterpriseLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel2.setText("Enterprise :");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        valueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        valueLabel1.setForeground(new java.awt.Color(188, 188, 188));
        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(188, 188, 188));
        enterpriseLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel1.setText("Treasurer Work Queue");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, -1, -1));

        btnAssign1.setBackground(new java.awt.Color(22, 27, 34));
        btnAssign1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssign1.setForeground(new java.awt.Color(188, 188, 188));
        btnAssign1.setText("Assign to Me");
        btnAssign1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAssign1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAssign1FocusLost(evt);
            }
        });
        btnAssign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssign1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssign1MouseExited(evt);
            }
        });
        btnAssign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssign1ActionPerformed(evt);
            }
        });
        add(btnAssign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 216, 36));

        btnCompleteDelivery.setBackground(new java.awt.Color(22, 27, 34));
        btnCompleteDelivery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCompleteDelivery.setForeground(new java.awt.Color(188, 188, 188));
        btnCompleteDelivery.setText("Process Request");
        btnCompleteDelivery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCompleteDeliveryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCompleteDeliveryFocusLost(evt);
            }
        });
        btnCompleteDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompleteDeliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompleteDeliveryMouseExited(evt);
            }
        });
        btnCompleteDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteDeliveryActionPerformed(evt);
            }
        });
        add(btnCompleteDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 216, 36));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(255, 255, 255));
        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
        btnLogoutPatient.setForeground(new Color(188, 188, 188));
        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        jPanel.removeAll();
        LoginJPanel lp = new LoginJPanel(ecoSystem, dB4OUtil, jPanel);
        jPanel.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) jPanel.getLayout();
        crdLyt.next(jPanel);
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void btnAssign1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAssign1FocusGained
        // TODO add your handling code here:
        btnAssign1.setForeground(new Color(255, 255, 255));
        btnAssign1.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAssign1FocusGained

    private void btnAssign1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAssign1FocusLost
        // TODO add your handling code here:
        btnAssign1.setForeground(new Color(188, 188, 188));
        btnAssign1.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAssign1FocusLost

    private void btnAssign1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssign1MouseEntered
        // TODO add your handling code here:
        btnAssign1.setForeground(new Color(255, 255, 255));
        btnAssign1.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAssign1MouseEntered

    private void btnAssign1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssign1MouseExited
        // TODO add your handling code here:
        btnAssign1.setForeground(new Color(188, 188, 188));
        btnAssign1.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAssign1MouseExited

    private void btnAssign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssign1ActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a record to be assigned", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            WorkRequest request = (NGOFundRequest) workRequestJTable.getValueAt(selectedRow, 5);
            if (request.getStatus().equals("Sent to Treasurer")) {
                request.setReceiver(userAccount);
                request.setStatus("Pending on " + request.getReceiver().getEmp().getEmpName());
                populateTable();
                JOptionPane.showMessageDialog(null, "Success. Request is assigned to you", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Cannot assign this work request, as the work request is in " + request.getStatus() + " status", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssign1ActionPerformed

    private void btnCompleteDeliveryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryFocusGained
        // TODO add your handling code here:
        btnCompleteDelivery.setForeground(new Color(255, 255, 255));
        btnCompleteDelivery.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCompleteDeliveryFocusGained

    private void btnCompleteDeliveryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryFocusLost
        // TODO add your handling code here:
        btnCompleteDelivery.setForeground(new Color(188, 188, 188));
        btnCompleteDelivery.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnCompleteDeliveryFocusLost

    private void btnCompleteDeliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryMouseEntered
        // TODO add your handling code here:
        btnCompleteDelivery.setForeground(new Color(255, 255, 255));
        btnCompleteDelivery.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCompleteDeliveryMouseEntered

    private void btnCompleteDeliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryMouseExited
        // TODO add your handling code here:
        btnCompleteDelivery.setForeground(new Color(188, 188, 188));
        btnCompleteDelivery.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnCompleteDeliveryMouseExited

    private void btnCompleteDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a row process", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            NGOFundRequest request = (NGOFundRequest) workRequestJTable.getValueAt(selectedRow, 5);
            if (request.getStatus().equalsIgnoreCase("Sent to Treasurer")) {
                JOptionPane.showMessageDialog(null, "Request has already been processed", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (request.getStatus().equalsIgnoreCase("Accepted")) {
                JOptionPane.showMessageDialog(null, "Request already accepted", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!userAccount.equals(request.getReceiver())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!userAccount.equals(request.getReceiver())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!userAccount.getEmp().equals(request.getReceiver().getEmp())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other auditor", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (request.getStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a rejected request", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            NGOTreasurerProcessWorkRequestJPanel treasurerProcessWorkRequestJPanel = new NGOTreasurerProcessWorkRequestJPanel(jPanel, request);
            jPanel.add("TreasurerProcessWorkRequestJPanel", treasurerProcessWorkRequestJPanel);
            CardLayout layout = (CardLayout) jPanel.getLayout();
            layout.next(jPanel);
        }
    }//GEN-LAST:event_btnCompleteDeliveryActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : treasurerOrganization.getWorkQueue().getWorkRequests()) {
            String status = request.getStatus();
            Object[] row = new Object[6];
            row[0] = request.getSender().getEmp().getEmpName();
            if (status.equalsIgnoreCase("Sent to Treasurer") || status.equalsIgnoreCase("Sent to Secretary")) {
                row[1] = null;
            } else {
                row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmp().getEmpName();
            }

            row[2] = status;
            row[3] = ((NGOFundRequest) request).getAmount();
            row[4] = ((NGOFundRequest) request).getMessage();
            row[5] = request;

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        workRequestJTable.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign1;
    private javax.swing.JButton btnCompleteDelivery;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
